config/routes.rb
Rails.application.routes.draw do
  resources :projects
  post "/rate" => "rater#create", :as => "rate"
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  mount Sidekiq::Web => "/sidekiq" # monitoring console
  resources :profiles

  authenticated :user, ->(u) { u.recruiter? || u.admin? } do
    root "profiles#index", as: :root
  end
  root "home#index"
  match "*unmatched", to: "errors#route_not_found", via: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flash.html.erb
<%# Notice %>
<% if flash[:notice].present? %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<%# Alert %>
<% if flash[:alert].present? %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>

app/views/shared/_footer.html.erb
<hr>

<footer>
  <p>© Smart Hired <%= Time.zone.now.strftime("%Y") %></p>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to("Smart Hired", root_path, class: "navbar-brand") %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
          <a href="#contact"></a>
        </li>
        <li class="dropdown">
          <ul class="dropdown-menu">
            <li>
              <a href="#"></a>
            </li>
            <li>
              <a href="#"></a>
            </li>
            <li>
              <a href="#"></a>
            </li>
            <li class="divider"></li>
            <li class="dropdown-header"></li>
            <li>
              <a href="#"></a>
            </li>
            <li>
              <a href="#"></a>
            </li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "My profile", edit_profile_path(current_user.profile) %></li>
          <% if current_user.recruiter? || current_user.admin? %>
          <li><%= link_to "Projects", projects_path %></li>
          <% end  %>

          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to('LogIn', new_user_session_path)%></li>
        <% end %>
      </ul>
    </div>
    <!--/.nav-collapse -->
  </div>
</div>